services:
  # Backend service (Go API)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: petamini-backend
    ports:
      - '8080:8080'
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - PORT=8080
      - ENVIRONMENT=production
    restart: unless-stopped
    networks:
      - petamini-network
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:8080/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend service (React + Nginx)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petamini-frontend
    ports:
      - '80:80'
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - petamini-network
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:80',
        ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  petamini-network:
    driver: bridge
